name: Node.js Package

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          registry-url: "https://registry.npmjs.org"
          cache: pnpm
      # TODO: remove it when Node.js v24 is LTS
      - run: npm install -g npm@latest
      - run: |
          pnpm install
          pnpm build
      - run: pnpm publish --provenance --access public --no-git-checks
